dist: focal

language: java

jdk:
 - oraclejdk11

services:
 - mongodb

addons:
  postgresql: "13"

before_install:
 # See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
 - rm ~/.m2/settings.xml
 # We need GraphViz to generate images
 - "sudo apt-get install graphviz 2>&1 | tail -n 2"

before_script:
 - psql --version
 - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
 - psql -c 'CREATE DATABASE fulltexttest;' -U postgres
 - psql -c 'CREATE USER testfts PASSWORD '"'testfts'"';' -U postgres fulltexttest
 - psql -c 'GRANT ALL ON DATABASE fulltexttest to testfts' -U postgres fulltexttest

#script: mvn -B -V install && mvn -B -V -Pexamples install
script: mvn -version
